<h1>Quick Numpy-tensor Learning</h1>

<h2>Create a tensor</h2>

Like numpy, tensor in pytorch is a very useful package, but we don’t need to learn it systematically. The most effective way is to understand the main methods and master and expand them in practical applications.

In [19]:
import numpy as np
import torch

 I don't want to introduce what is array, and I will directly give the usual function to new a tensor.

In [20]:
torch.tensor([1, 2, 3, 4])    # by list 

tensor([1, 2, 3, 4])

In [21]:
# by space the series
m1 = torch.linspace(1, 10, 3)    # the parameter 'step' is numbers we get
m2 = torch.logspace(1, 10, 3)
m3 = torch.arange(1, 10, 3)    # the parameter 'step' is the step
print(m1)
print(m2)
print(m3)

tensor([ 1.0000,  5.5000, 10.0000])
tensor([1.0000e+01, 3.1623e+05, 1.0000e+10])
tensor([1, 4, 7])


In [22]:
# Special but commonly used
m4 = torch.eye(3, 4)    # the shape dimension is 2
m5 = torch.ones(2, 4, 2)
m6 = torch.zeros(2, 4, 2)
m7 = torch.rand(2, 4, 2)
print(m4)
print(m7)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])
tensor([[[0.3296, 0.8415],
         [0.5794, 0.6501],
         [0.1551, 0.7829],
         [0.8113, 0.9307]],

        [[0.9159, 0.3593],
         [0.5258, 0.8536],
         [0.6976, 0.9222],
         [0.9989, 0.2667]]])


Of course there are many ways, such as `ones_like`, `zeros_like`, `from_Numpy` and so on. Here we don't introduce more.

**The differences between `torch.Tensor` and `torch.tensor`** 
  
1.`torch.Tensor` is a mix of `torch.empty` and `torch.tensor`. But when incoming data, `torch.Tensor` uses Tensor's global default dtype (FloatTensor) by default, but `torch.tensor` will judge from the data.  
2.`torch.tensor(1)` return the digit 1, but `torch.Tensor(1)` return a tensor that size is one and the vaule is random.


In [25]:
t1 = torch.tensor(1)
t2 = torch.Tensor(1)
print(t1, t1.dtype)
print(t2, t2.dtype)

tensor(1) torch.int64
tensor([0.]) torch.float32


<h2>Modify tensor shape</h2>

In [32]:
n1 = torch.rand(5, 6)
print(n1.size())    # size() is equal to shape, and the same as resize and reshape
print(n1.shape)
print(torch.numel(n1))


torch.Size([5, 6])
torch.Size([5, 6])
30
